# Generated by Django 5.2.4 on 2025-12-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appointment_contact_number_appointment_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_seen_by_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
